# 配置的base属性
server:
  port: 4000

spring:
  application:
    name: ocean

druid:
  # 数据源配置
  user: zhian
  password: Zhian+1234567890
  driverClass: com.mysql.cj.jdbc.Driver
  # 初始化 最小 最大
  initialSize: 5
  minIdle: 5
  maxActive: 20
  testOnBorrow: false
  urlIceberg: jdbc:mysql://39.107.248.247:3306/zhian?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false
  urlOcean: jdbc:mysql://119.3.126.254:3308/JTYS?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false
#  urlAccount: jdbc:mysql://106.12.176.120/account?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false  # 设置时区

